if("${PAPAGENO_TEST_EXECUTABLE}" STREQUAL "")
   message(FATAL_ERROR "No PAPAGENO_TEST_EXECUTABLE provided")
endif()

 if("${PAPAGENO_COMPRESSED_CODE_FILE}" STREQUAL "")
   message(FATAL_ERROR "No PAPAGENO_COMPRESSED_CODE_FILE provided")
endif()  

if(NOT EXISTS "${PAPAGENO_TEST_EXECUTABLE}")
   message("Cannot find test executable ${PAPAGENO_TEST_EXECUTABLE}")
   
   if(EXISTS "${PAPAGENO_COMPRESSED_CODE_FILE}")
      file(REMOVE "${PAPAGENO_COMPRESSED_CODE_FILE}")
   endif()
endif()

message("Executing ${PAPAGENO_RUN_WRAPPER} ${PAPAGENO_TEST_EXECUTABLE}")

if(NOT "${PAPAGENO_RUN_WRAPPER}" STREQUAL "")
   set(output_file "${PAPAGENO_COMPRESSED_CODE_FILE}.tmp")
   set(file_indicator ERROR_FILE)
else()
   set(output_file "${PAPAGENO_COMPRESSED_CODE_FILE}")
   set(file_indicator OUTPUT_FILE)
endif()

execute_process(COMMAND ${PAPAGENO_RUN_WRAPPER} "${PAPAGENO_TEST_EXECUTABLE}"
                ${file_indicator} "${output_file}")
                
if(NOT "${PAPAGENO_RUN_WRAPPER}" STREQUAL "")
   execute_process(
      COMMAND cat "${output_file}"
      COMMAND sed "s/\\.\\.\$//" # Remove dots at end of the line as generated by simavr
      COMMAND sed "0,/__PPG_START_OF_GENERATED_CODE__/d" # Remove any lines before generated code
      COMMAND sed "/__PPG_END_OF_GENERATED_CODE__/,$ d" # Remove any lines after generated code
      COMMAND sed -r "s/\\x1b\\[([0-9]{1,2}(;[0-9]{1,2})*)?m//g" # Remove coloring escape sequences
      
      OUTPUT_FILE "${PAPAGENO_COMPRESSED_CODE_FILE}"
   )
endif()