set(__PPG_MAX_EVENTS 100)

set(__PPG_MAX_INPUTS 256)

set(__PPG_SMALL_UNSIGNED_INT_TYPE uint8_t)

set(__PPG_SMALL_SIGNED_INT_TYPE int8_t)

set(__PPG_MEDIUM_SIGNED_INT_TYPE int16_t)
   
if(PAPAGENO_PEDANTIC_TOKENS)
   set(__PPG_PEDANTIC_TOKENS 1)
else()
   set(__PPG_PEDANTIC_TOKENS 0)
endif()

set(__PPG_COUNT_TYPE ${__PPG_SMALL_UNSIGNED_INT_TYPE})

set(__PPG_ID_TYPE ${__PPG_MEDIUM_SIGNED_INT_TYPE})

set(__PPG_ACTION_FLAGS_TYPE ${__PPG_SMALL_UNSIGNED_INT_TYPE})

set(__PPG_LAYER_TYPE ${__PPG_SMALL_SIGNED_INT_TYPE})

set(__PPG_SLOT_ID_TYPE ${__PPG_SMALL_UNSIGNED_INT_TYPE})

set(__PPG_TIME_COMPARISON_RESULT_TYPE ${__PPG_SMALL_SIGNED_INT_TYPE})

set(__PPG_EVENT_BUFFER_INDEX_TYPE ${__PPG_SMALL_SIGNED_INT_TYPE})

set(__PPG_PROCESSING_STATE_TYPE ${__PPG_SMALL_UNSIGNED_INT_TYPE})

set(__PPG_TIME_IDENTIFIER_TYPE uintptr_t)
#set(__PPG_TIME_IDENTIFIER_TYPE long unsigned)

set(__PPG_TIME_IDENTIFIER_TYPE PPG_Time)

set(__PPG_PRINT_SELF_ENABLED)

set(__PPG_HAVE_ASSERTIONS)
