/* Copyright 2017 Florian Fleissner
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef PPG_CLUSTER_H
#define PPG_CLUSTER_H

#include "ppg_token.h"
#include "ppg_input.h"
#include "ppg_layer.h"

/** @brief Defines a stand alone note cluster. 
 * 
 * All members must be activated/pressed at 
 * least once for	the cluster to be considered as completed.
 * 
 * @param layer The layer the pattern is associated with
 * @param action The action that is supposed to be carried out if the pattern is completed
 * @param n_inputs The number of inputs
 * @param inputs A pointer to an array of input definitions.
 * @param n_members The number of cluster members that must match the size of the inputs array.
 * @returns The constructed token
 */
PPG_Token ppg_cluster(		
							PPG_Layer layer, 
							PPG_Action action,
							PPG_Count n_inputs, 
							PPG_Input inputs[]);

/** @brief Generates a cluster token.
 *
 * Use this function to generate tokens that are passed to the ppg_pattern function
 * to generate complex patterns. Every member of the cluster must have been
 * activated at least once for the cluster to be considered as completed.
 * 
 * @note Clusters that are generated by this function must be passed to ppg_pattern
 * 		to be effective
 * @note Use setter functions that operate on tokens to change attributes of the generated token 
 * 
 * @param n_inputs The number of inputs that are associated with the cluster 
 * @param inputs An array of input ids that represent the notes of the cluster
 * @returns The constructed token
 */
PPG_Token ppg_create_cluster(
							PPG_Count n_inputs,
							PPG_Input inputs[]);

/** @brief Auxiliary macro to create a cluster based on a set of input specifications
 * 
 * @param ... A list of inputs
 */
#define PPG_CREATE_CLUSTER(...) \
	ppg_create_cluster(PPG_INPUTS(__VA_ARGS__))

#endif
