/* Copyright 2017 Florian Fleissner
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef PPG_CHORD_H	
#define PPG_CHORD_H

/** @brief Defines a stand alone magic chord. 
 * 
 * All members must be activated/pressed simultaneously
 * for a chord to be considered as completed.
 * 
 * @param layer The layer the pattern is associated with
 * @param action The action that is supposed to be carried out if the pattern is completed
 * @param n_inputs The number of inputs
 * @param inputs A pointer to an array of input definitions.
 * @param n_members The number of chord members that must match the size of the inputs array.
 * @returns The constructed token
 */
PPG_Token ppg_chord(		
							uint8_t layer,
							PPG_Action action,
							uint8_t n_inputs,
							PPG_Input inputs[]);

/** @brief Generates a chord token.
 * 
 * Use this function to generate tokens that are be passed to the ppg_pattern function
 * to generate complex patterns. All notes of a chord must have been pressed
 * at the same time time for the chord to be completed.
 * 
 * @note Chords that are generated by this function must be passed to ppg_pattern
 * 		to be effective
 * @note Use setter functions that operate on tokens to change attributes of the generated token 
 * 
 * @param n_inputs The number of inputs that are associated with the chord 
 * @param inputs An array of inputs that represent the notes of the chord
 * @returns The constructed token
 */
PPG_Token ppg_create_chord(	
							uint8_t n_inputs,
							PPG_Input inputs[]
							);

/** @brief Auxiliary macro to create a chord based on a set of input specifications
 * 
 * @param ... A list of inputs
 */
#define PPG_CREATE_CHORD(...) \
	ppg_create_chord(PPG_KEYS(__VA_ARGS__))
	
#endif
